project_name: dockle
builds:
- main: cmd/dockle/main.go
  binary: dockle
  ldflags:
  - -s -w
  - "-extldflags '-static'"
  - -X main.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  - freebsd
  - openbsd
  goarch:
  - amd64
  - 386
  - arm
  - arm64
  goarm:
  - 7

nfpm:
  formats:
  - deb
  - rpm
  vendor: "goodwithtech"
  homepage: "https://github.com/goodwithtech"
  maintainer: "Tomoya Amachi <tomoya.amachi@gmail.com>"
  description: "A Security and Dockerfile checker for Containers"
  license: "AGPL"
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD

archive:
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  files:
  - README.md
  - LICENSE

brews:
  github:
    owner: goodwithtech
    name: homebrew-dockle
  folder: Formula
  homepage: https://github.com/goodwithtech/dockle
  description: Simple Security Auditing and helping build the Best Docker Images
  test: |
    system "#{bin}/program --version"
