on:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - run: docker build . -t ${{ github.sha }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        image-ref: ${{ github.sha }}
        severity: CRITICAL
        ignore-unfixed: true
        exit-code: '1'
    - name: Run Dockle container linter
      uses: goodwithtech/dockle-action@e30e6af832aad6ea7dca2a248d31a85eab6dbd68 # v0.4.15
      with:
        image: ${{ github.sha }}
        exit-code: '1'
        exit-level: warn
